// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-east-1:3853ec9a-5ea3-4d10-978a-3249b484a9d0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_wArJ1EovZ",
    "aws_user_pools_web_client_id": "2ka0lqb0nr88ubgk4hcslk3s3c",
    "oauth": {},
    "aws_user_files_s3_bucket": "s3webcamuploader83a65c76f8384092b63d212639122190",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
